/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'system-ui', 'sans-serif'],
        serif: ['IBM Plex Serif', 'Georgia', 'serif'],
        'headline-xl': ['Newsreader', 'Georgia', 'serif'],
        'headline-lg': ['Newsreader', 'Georgia', 'serif'],
        'headline-md': ['Newsreader', 'Georgia', 'serif'],
        'body-sm': ['Manrope', 'system-ui', 'sans-serif'],
        'body-md': ['Manrope', 'system-ui', 'sans-serif'],
        'body-lg': ['Manrope', 'system-ui', 'sans-serif'],
        'label-caps': ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      spacing: {
        gutter: '24px',
        'element-gap': '16px',
        'section-gap': '80px',
        'margin-x': '32px',
      },
      colors: {
        'on-surface-variant': '#404940',
        'outline-variant': '#bfc9bd',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed-dim': '#e9c349',
        surface: '#f7f9fb',
        'on-surface': '#191c1e',
        'on-error': '#ffffff',
        primary: '#004c22',
        'surface-bright': '#f7f9fb',
        background: '#f7f9fb',
        'on-tertiary-container': '#a6dbaf',
        'tertiary-fixed': '#b9f0c2',
        'inverse-primary': '#8bd79b',
        'on-tertiary-fixed': '#00210c',
        'on-primary-fixed-variant': '#005226',
        'surface-container': '#eceef0',
        'on-secondary-container': '#745c00',
        tertiary: '#184a29',
        'surface-container-low': '#f2f4f6',
        'surface-variant': '#e0e3e5',
        'on-background': '#191c1e',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary': '#ffffff',
        outline: '#707a6f',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#31623f',
        'on-secondary-fixed-variant': '#574500',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#9ed3a7',
        'primary-container': '#166534',
        'surface-container-highest': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'primary-fixed': '#a6f4b5',
        'on-primary-fixed': '#00210b',
        'surface-tint': '#1f6c3a',
        'error-container': '#ffdad6',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#1f502f',
        'on-secondary-fixed': '#241a00',
        'surface-container-high': '#e6e8ea',
        'primary-fixed-dim': '#8bd79b',
        'secondary-fixed': '#ffe088',
        'on-primary-container': '#93e0a2',
        secondary: '#735c00',
        viva: {
          50: '#eff8f7',
          100: '#e3f4f2',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#115e59',
          800: '#134e4a',
          900: '#0c4483',
          950: '#042f2e',
        },
        coop: {
          50: '#eff8f7',
          100: '#e3f4f2',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#14b8a6',
          600: '#0d9488',
          700: '#115e59',
          800: '#134e4a',
          900: '#0c4483',
          950: '#042f2e',
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.5s ease-out forwards',
        'fade-in': 'fadeIn 0.2s ease-out forwards',
        'slide-in-right': 'slideInRight 0.3s ease-out forwards',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(100%)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}
